replicaCount: 1

image:
  repository: harbor.devops.qdb.com/devops/openresty
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.17.8.2-lua-4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "sllc"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


hostNetwork: false
command: ["/usr/local/openresty/bin/openresty"]
args: ["-g", "daemon off;", "-c", "/usr/local/openresty/nginx/conf/nginx.conf"]


config: |
  worker_processes auto;
  events {
    worker_connections 1024;
  }

  http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name localhost;
        root /usr/local/openresty/nginx/html;
        index index.html;

        # 处理 /chat/static/ 路径下的静态资源
        location /chat/static/ {
            alias /usr/local/openresty/nginx/html/;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # 将根路径重定向到 /chat/static/
        location = / {
            return 301 /chat/static/index.html;
        }

        # 处理其他请求
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
  }



ports:
  - name: sllc
    containerPort: 8080
    protocol: TCP

service:
  type: ClusterIP
  port:
    - name: sllc
      protocol: TCP
      port: 8080
      targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/real-ip-header: X-Forwarded-For
    nginx.ingress.kubernetes.io/set-real-ip-from: 0.0.0.0/0
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    - host: sllc.devops.qdb.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePortName: sllc
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

nodeSelector: {}
  # kubernetes.io/hostname: "devwork1"


tolerations: []

affinity: {}

envs:
  - name: LUAJIT_LIB
    value: "/usr/local/openresty/luajit/lib"
  - name: LUAJIT_INC
    value: "/usr/local/openresty/luajit/include/luajit-2.1"

hostAliases: {}
  # - hostnames:
  #   - "tdh01"
  #   - "test"
  #   ip: "10.1.91.159"
  # - hostnames: 
  #   - "tdh02"
  #   ip: "10.1.91.161"


volumeMounts: 
  - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
    name: config
    subPath: nginx.conf
volumes:
  - configMap:
      name: sllc-config
    name: config
